import yaml

from snakemake.utils import min_version, validate

# Limit the snakemake version to a modern one.
min_version("8.10")

# Load the default configuration. This will be overridden by users.
configfile: "config/default.yaml"
# Validate the configuration using the schema file.
validate(config, workflow.source_path("schemas/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/internal_config.yaml"), "r") as f:
    internal = yaml.safe_load(f)

# Add all your includes here.
include: "rules/downloads.smk"
include: "rules/energy_balances.smk"
include: "rules/jrc_industry.smk"

rule all:
    message: "Generate all outputs for 'industry'."
    input:
        rules.annual_energy_balances.output,
        "results/processed_industry_energy.nc",
        "results/processed_industry_production.nc",
