name: ec-atlite-availability-matrix
description:
url: https://github.com/calliope-project/ec_modules/wrappers/atlite/
authors:
  - Ivan Ruiz Manuel
input:
  - cutout: atlite Cutout file.
  - shapefile: Shapefile to use for regions.
  - rasters: One or more raster files to use for filtering.
output:
  - availability: NetCDF file with post-filtering availability.
  # Optional
  - plot_raster_result: Figure showing the filtered area and its position in the cutout.
  - plot_availability: Figure showing resulting availability matrix.
params:
  - availability_name: xarray name for the availability.
  - exclusion_crs: projected CRS to use for raster analysis.
  - exclusion_resolution: resolution to use for raster analysis.
  - shapefile_name_column: Column with the names of regions in the shapefile.
  - raster_codes: Per raster, a list of codes to filter.
  - raster_kwargs: Per raster, kwargs for the `add_raster` function (use `{}` if empty).
  # Optional
  - exclusion_kwargs: dict. Additional `ExclusionContainer` parameters.
  - availability_kwargs: dict. Additional `availabilitymatrix` parameters.
