name: default
channels:
    - conda-forge
dependencies:
    - python=3.9
    - ipython=7.21.0
    - ipdb=0.13.13
    - numpy=1.20.3
    - pandas=1.2.3
    - geopandas=0.13.2
    - bottleneck=1.3.2
    - xlrd=2.0.1
    - openpyxl=3.0.7
    - pycountry=18.12.8
    - jinja2=2.11.3
    - pip=21.0.1
    - xarray=0.17.0
    - netCDF4=1.6.2
    - hdf5=1.12.2
    - libnetcdf=4.8.1
    - scipy=1.9.1
    - dask=2023.2.0
    - pip:
        - "git+https://github.com/calliope-project/ec_utils.git@v0.1.0"
        - styleframe==4.2
