rule test:
    input:
        shapefile = "portugal.geojson"
    output:
        cutout = "output/cutout.nc",
        plot_cutout = "output/plot_cutout.png"
    params:
        time = "2019-05-02",
        features = ["influx", "temperature", "wind"],
        offset_degrees = 1,
        module = ["era5"],
    threads: 4
    wrapper: "file:../"
