rule test:
    input:
        shapefile = "montenegro.geojson"
    output:
        cutout = "output/cutout.nc",
        plot_cutout = "output/plot_cutout.png"
    params:
        time = "2019-05-02",
        features = ["height", "wind", "influx", "temperature", "runoff"],
        offset_degrees = 1,
        module = ["era5"],
    threads: 1
    wrapper: "file:../"
