$schema: https://json-schema.org/draft/2020-12/schema
type: object
additionalProperties: false
properties:
    shapefile:
      type: object
      additionalProperties: false
      description: Settings related to shapes.
      properties:
        path:
          type: string
          description: url, full path or relative path to the shapefile.
        download:
          type: boolean
          description: If True, the module will attempt to download the shapefile from the url in 'path'.
        country-id-column:
          type: string
          description: name of the column containing ISO country codes in alpha-3 format.
        subregion-id-column:
          type: string
          description: name of the column containing unique subregion IDs.
    year-slice:
      type: array
      description: range of years to process.
      items:
        type: number
