default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Machine-friendliness
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Repo quality
      - id: check-added-large-files
        args: ['--maxkb=250', --enforce-all]
      - id: forbid-submodules
      - id: check-case-conflict
      # - id: check-illegal-windows-names  TODO: reactivate once https://github.com/pre-commit/pre-commit-hooks/issues/1048 is fixed
      - id: check-merge-conflict
      - id: debug-statements
      # Config file issues
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
