# This file contains configuration that users should not modify.
resources:
  default_user_shapes: https://www.dropbox.com/scl/fi/ijfihaqy5eki13nplvrn4/units-ehighways.geojson?rlkey=q0agmofhaklt1pytzef59o1xq&e=1&dl=0
  load: https://data.open-power-system-data.org/time_series/2019-06-05/time_series_60min_stacked.csv
  potentials: https://zenodo.org/records/6600619/files/raw-potentials.zip?download=1

scaling_factors: # values are tuned for models with a few hours resolution and one year duration
    power: 0.00001 # from MW(h) to 100 GW(h)
scope:
    spatial:
        countries:
            - "Austria"
            - "Belgium"
            - "Bulgaria"
            - "Croatia"
            - "Cyprus"
            - "Czech Republic"
            - "Denmark"
            - "Estonia"
            - "Finland"
            - "France"
            - "Germany"
            - "Greece"
            - "Hungary"
            - "Ireland"
            - "Italy"
            - "Latvia"
            - "Lithuania"
            - "Luxembourg"
            - "Netherlands"
            - "Poland"
            - "Portugal"
            - "Romania"
            - "Slovakia"
            - "Slovenia"
            - "Spain"
            - "Sweden"
            - "United Kingdom"
            - "Albania"
            - "Bosnia and Herzegovina"
            - "Macedonia, Republic of"
            - "Montenegro"
            - "Norway"
            - "Serbia"
            - "Switzerland"
        bounds:
            x_min: -15.8
            x_max: 37
            y_min: 30
            y_max: 75
quality_control:
  load:
      outlier-data-thresholds:
          relative-to-mean-min: 0.25
          relative-to-mean-max: 2
      max-interpolate-timesteps: 3
      acceptable-year-diff-for-gap-filling: 5
      fill-29th-feb-from-28th: true
      data-source-priority-order:
          - actual_entsoe_transparency
          - actual_entsoe_power_statistics
