import glob
from pathlib import Path

from snakemake.utils import validate, min_version, makedirs

min_version("8.10")

configfile: "../config/default.yaml"

wildcard_constraints:
    resolution = "[a-zA-Z]+"

rule units:
    message: "Download spatial zones for {wildcards.resolution}."
    params:
        url = config["resolution-file"],
    output: "results/{resolution}/units.geojson"
    conda: "./envs/shell.yaml"
    shell: "curl -sSLo {output} '{params.url}'"

include: "./rules/hydro.smk"

rule all:
    localrule: True
    default_target: True
    input:
        expand("results/{resolution}/capacityfactors-hydro-run-of-river-{first_year}-{final_year}.csv",
            resolution=config["resolution-name"],
            first_year=config["first-year"],
            final_year=config["final-year"]),
        expand("results/{resolution}/capacityfactors-hydro-reservoir-{first_year}-{final_year}.csv",
            resolution=config["resolution-name"],
            first_year=config["first-year"],
            final_year=config["final-year"]),
        expand("results/{resolution}/supply-hydro.csv", resolution=config["resolution-name"]),
        expand("results/{resolution}/storage-hydro.csv", resolution=config["resolution-name"]),
