# This file contains configuration that users should not modify.
default_resources:
  spatial_units: https://www.dropbox.com/scl/fi/sjjisuqnzck2mhxs9jca7/units-{resolution}.geojson?rlkey=rv0q1exsytxws3gfvankbt9p7&e=1&dl=0
resources:
  eez: https://sandbox.zenodo.org/records/45135/files/eez_v11.gpkg.zip?download=1  # FIXME: update to actual zenodo record before next Euro-Calliope release.
  capacity-factors: https://zenodo.org/record/3899687/files/{filename}?download=1
capacity-factors:
    min: 0.001
    trim-ninja-timeseries: True
quality-control:
    capacity-factor-gridcell-overlap-threshold: 0.97 # Ceuta y Melilla has smallest overlap
    shared-coast-polygon-area-share-threshold: 0.01
scope:
  spatial:
      countries:
          - "Austria"
          - "Belgium"
          - "Bulgaria"
          - "Croatia"
          - "Cyprus"
          - "Czech Republic"
          - "Denmark"
          - "Estonia"
          - "Finland"
          - "France"
          - "Germany"
          - "Greece"
          - "Hungary"
          - "Ireland"
          - "Italy"
          - "Latvia"
          - "Lithuania"
          - "Luxembourg"
          - "Netherlands"
          - "Poland"
          - "Portugal"
          - "Romania"
          - "Slovakia"
          - "Slovenia"
          - "Spain"
          - "Sweden"
          - "United Kingdom"
          - "Albania"
          - "Bosnia and Herzegovina"
          - "Macedonia, Republic of"
          - "Montenegro"
          - "Norway"
          - "Serbia"
          - "Switzerland"
      bounds:
          x_min: -15.8
          x_max: 37
          y_min: 30
          y_max: 75
