name: ec-atlite-csp-cf-series
description:
url: https://github.com/calliope-project/ec_modules/wrappers/atlite/
authors:
  - Ivan Ruiz Manuel
input:
  - cutout: atlite cutout netCDF with relevant wind data.
  - shapefile: file with the regions to process.
output:
  - timeseries: CSP capacity factor time series (row::observation column::region).
  # Optional
  - plot_mean_cf: map with average capacity factor per region.
params:
  - shapefile_name_column: Column to use as region names (will be column names in timeseries file).
  - installation: Name of a compatible atlite CSP installation.
  # Optional
  - shapefile_specific_names: Names(s) of regions to calculate specifically. Others will be ignored.
  - cutout_kwargs: Additional arguments for processing the Cutout.
  - csp_kwargs: Additional arguments for the wind function.
note: Please see atlite docs/code for more information on parameter | kwarg options.
