# Module input files by users go here.
use_default_customisable_resources: True
resolution: "ehighways"

# Any other user configuration goes below
scope:
  temporal:
      first-year: 2016
      final-year: 2016
