# Module input files by users go here.
use_default_resources: True


# Any other user configuration goes below
resolution: "ehighways"
scope:
  temporal:
      first-year: 2016
      final-year: 2016
