# Module input files by users go here.
resources:
  download: True
  spatial_units: https://www.dropbox.com/scl/fi/sjjisuqnzck2mhxs9jca7/units-{resolution}.geojson?rlkey=rv0q1exsytxws3gfvankbt9p7&e=1&dl=0

# Any other user configuration goes below
resolution: "ehighways"
scope:
  temporal:
      first-year: 2016
      final-year: 2016
capacity-factors:
    min: 0.001
    max: 10 # 0.001 -> 10 leads to a numerical range of 1e5 (hourly resolution)
    average:
        pv: 0.139 # median of average 2016 open-field factors for ~2700 points in Europe
        onshore: 0.3021 # median of average 2016 factors for ~2700 points in Europe
        offshore: 0.4223 # median of average 2016 factors for ~2800 points in Europe
        ror: 0.536781 # median of average 2016 factors for 1889 hydro stations in Europe
    trim-ninja-timeseries: True
