
rule ppm_powerplants:
    output:
        powerplants= "results/powerplants.csv",
        stats_aggregated = "results/stats_aggregated.png",
    params:
        from_url= False
    threads: 1
    wrapper: "file:../"
