# This is the default configuration of your module
data-sources:
  resolution: "national"
  spatial-zones: "https://www.dropbox.com/scl/fi/sjjisuqnzck2mhxs9jca7/units-national.geojson?rlkey=rv0q1exsytxws3gfvankbt9p7&dl=0"
parameters:
  transport:
      future-vehicle-efficiency-percentile: 0.25 # FIXME Why so low? Why not 0.5?
      # FIXME road-transport-conversion-factors are redundant, as they are derived using future-vehicle-efficiency-percentile
      road-transport-conversion-factors: # MWh / mio km 25th percentile efficiency of all countries in 2015 [@Mantzos:2017]
        light-duty-vehicles: 480
        heavy-duty-vehicles: 3248 # based on buses
        coaches-and-buses: 3248
        passenger-cars: 324
        motorcycles: 200  # based on passenger car electrical efficiency scaled by relative diesel efficiency
      vehicle-type-names:
        light-duty-vehicles: Light duty vehicles
        heavy-duty-vehicles: Heavy duty vehicles
        coaches-and-buses: Motor coaches, buses and trolley buses
        passenger-cars: Passenger cars
        motorcycles: Powered 2-wheelers
      ev-battery-sizes:
        heavy-duty-vehicles: 0.2  # average from [@EUCAR:2019]
        light-duty-vehicles: 0.1  # own assumption based on passenger cars from [@EUCAR:2019]
        motorcycles: 0.01  # own assumption
        coaches-and-buses: 0.2  # own assumption based on HDVs from [@EUCAR:2019]
        passenger-cars: 0.08  # average from [@EUCAR:2019]
      uncontrolled-ev-charging-share: 0.8
      monthly-demand-bound-fraction:
        min: 0.9
        max: 1.1
        equals: 1
scope:
  temporal:
    first-year: 2016
    final-year: 2016
