DATAPATH = config["setup"]["datapath"]
OUTPATH = config["setup"]["outpath"]

rule create_local:
    message: "This thing just creates a file and nothing else."
    output:
        f"{DATAPATH}/local.txt"
    shell:
        "touch {output}"

rule process_local:
    message: "Needs a file from above."
    input:
        rules.create_local.output
    output:
        f"{DATAPATH}/subprocess_local.txt"
    shell:
        "touch {output}"

rule output:
    message: "This one emulates the last file you really care about in the module."
    input:
        rules.process_local.output
    output:
        f"{OUTPATH}/final.txt"
    shell:
        "touch {output}"
