$schema: https://json-schema.org/draft/2020-12/schema
description: "Configuration schema for 'capacity_factors_wind_pv'."
type: object
additionalProperties: false
properties:
  use_default_resources:
    type: boolean
    description: If True, the module will attempt to download default resource files instead of relying on custom user inputs.
  resolution:
    type: string
    description: The resolution of the data to be used. Options are 'ehighways' or 'ninja'.
  scope:
    temporal:
      type: object
      properties:
        first-year:
          type: integer
          description: The first year of the simulation.
        final-year:
          type: integer
          description: The final year of the simulation.
