DATAPATH = config["setup"]["datapath"]
OUTPATH = config["setup"]["outpath"]

# You must ensure rules are defined in order.
# Otherwise commands like "rules.rulename.output" won't work.
# See https://github.com/snakemake/snakemake/issues/2514

rule create_local:
    message: "This thing just creates a file and nothing else."
    output:
        f"{DATAPATH}/local.txt"
    shell:
        "touch {output}"

rule process_global:
    message: "Needs a file from above."
    input:
        config["inputs"]["global-subtask-path"],
        rules.create_local.output
    output:
        f"{DATAPATH}/process_global.txt"
    shell:
        "touch {output}"

rule process_local:
    message: "Needs a file from above."
    input:
        rules.create_local.output
    output:
        f"{DATAPATH}/process_local.txt"
    shell:
        "touch {output}"

rule output:
    message: "Last file(s) you really care about in the module."
    input:
        rules.process_global.output,
        rules.process_local.output
    output:
        f"{OUTPATH}/final.txt",
    shell:
        "touch {output}"
