rule test:
    input:
        cutout = "cutout.nc",
        availability_matrix = "availability.nc"
    output:
        layout = "output/layout.nc",
        plot_layout = "output/plot_layout.png"
    params:
        max_capacity_per_km2 = 5.1,
        layout_name = "test_layout",
        layout_crs = "3035"
    threads: 4
    wrapper: "file:../"
