name: atlite - pv-cf-series
description:
url: https://github.com/calliope-project/ec_modules/wrappers/atlite/
authors:
  - Ivan Ruiz Manuel
input:
  - cutout: atlite cutout netCDF with relevant PV data.
  - shapefile: file with the regions to process.
output:
  - timeseries: pv capacity factor time series (row::observation column::region).
  # Optional
  - plot_mean_cf: map with average capacity factor per region.
params:
  - shapefile_name_column: column to use as region names (will be column names in timeseries file).
  - pv_panel: name panel or dict with panel characteristics (see atlite docs).
  - pv_orientation: |
      either 'latitude_optimal' or dict in the form {'slope': 0.0, 'azimuth': 0.0}
  # Optional
  - shapefile_specific_names: name(s) of regions to calculate specifically. Others will be ignored.
  - cutout_kwargs: "additional arguments for processing the Cutout (e.g., {chunks: {'time': 20}})"
  - pv_tracking: "options: None | 'horizontal' | 'tilted_horizontal' | 'vertical' | 'dual'"
  - pv_kwargs: "additional arguments for the pv function (e.g., {tracking: 'horizontal'})"
notes: Requested shapes must be within the cutout!
