rule test:
    input:
        zipfile = "test.zip"
    output:
        shapefile = "output/regions.geojson",
        plot_shapefile = "output/regions.png"
    params:
        zip_filepath = "myshape/myshape.shp",
        to_file_kwargs = {
            "driver": "GeoJSON"
        }
    threads: 1
    wrapper: "file:../"
