rule tsam_timeseries:
    input:
        "testdata_GHI.csv",
        "testdata_T.csv"
    output:
        typical_periods = "results/typical_periods.csv",
        accuracy_indicators = "results/accuracy_indicators.csv",
        index_matching = "results/index_matching.csv"
    params:
        noTypicalPeriods = 8,
        hoursPerPeriod = 24,
        segmentation = True,
        noSegments = 8,
        representationMethod = "distributionAndMinMaxRepresentation",
        distributionPeriodWise = False,
        clusterMethod = 'hierarchical'
    threads: 4
    wrapper: "file:../"
