rule tsam_timeseries:
    input:
        "testdata1.csv",
        "testdata2.csv"
    output:
        typical_periods = "output/typical_periods.csv",
        accuracy_indicators = "output/accuracy_indicators.csv",
        index_matching = "output/index_matching.csv"
    params:
        noTypicalPeriods = 8,
        hoursPerPeriod = 24,
        segmentation = True,
        noSegments = 8,
        representationMethod = "distributionAndMinMaxRepresentation",
        distributionPeriodWise = False,
        clusterMethod = 'hierarchical'
    threads: 4
    wrapper: "file:../"
