rule atlite_availability:
    input:
        cutout = "MNE_cutout.nc",
        shapefile = "MNE.geojson",
        rasters = ["MNE_CORINE.tif"],
    output:
        availability_matrix = "results/test.nc",
        plot_availability_raster = "results/shape.png",
        plot_availability_matrix = "results/matrix.png"
    params:
        availability_name = "MNE availability",
        shapefile_index_column = "ADM0_A3",
        exclusion_container_kwargs = {
            "crs": 3035,
            "res": 100,
        },
        raster_codes = [[20, 21, 25, 43, 44]],
        raster_kwargs = [{"invert": False}]
    threads: 4
    wrapper: "file:../"

# Raster file:
# Generated using European Union's Copernicus Land Monitoring Service information;
# <https://doi.org/10.2909/960998c1-1870-4e82-8051-6485205ebbac>
