# This is the default configuration of your module
data-sources:
  when2heat-params: https://zenodo.org/records/10965295/files/{dataset}?download=1
  gridded-weather-data: https://zenodo.org/records/11516744/files/{data_var}.nc
  population: https://ec.europa.eu/eurostat/cache/GISCO/geodatafiles/JRC_GRID_2018.zip
  jrc-idees: https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/JRC-IDEES/JRC-IDEES-2015_v1/JRC-IDEES-2015_All_xlsx_{country_code}.zip
  eurostat-energy-balance: https://raw.githubusercontent.com/calliope-project/euro-calliope-datasets/feature-sector-coupling/eurostat/nrg_bal_c.tsv.gz # FIXME: move to zenodo
  eurostat-hh-end-use:  https://raw.githubusercontent.com/calliope-project/euro-calliope-datasets/feature-sector-coupling/eurostat/nrg_d_hhq.tsv.gz # FIXME: move to zenodo
  swiss-end-use: https://www.bfe.admin.ch/bfe/en/home/versorgung/statistik-und-geodaten/energiestatistiken/energieverbrauch-nach-verwendungszweck.exturl.html/aHR0cHM6Ly9wdWJkYi5iZmUuYWRtaW4uY2gvZGUvcHVibGljYX/Rpb24vZG93bmxvYWQvOTg1NA==.html
  swiss-energy-balance: https://www.bfe.admin.ch/bfe/en/home/versorgung/statistik-und-geodaten/energiestatistiken/gesamtenergiestatistik.exturl.html/aHR0cHM6Ly9wdWJkYi5iZmUuYWRtaW4uY2gvZGUvcHVibGljYX/Rpb24vZG93bmxvYWQvNzUxOQ==.html
  swiss-industry-energy-balance: https://www.bfe.admin.ch/bfe/en/home/versorgung/statistik-und-geodaten/energiestatistiken/teilstatistiken.exturl.html/aHR0cHM6Ly9wdWJkYi5iZmUuYWRtaW4uY2gvZGUvcHVibGljYX/Rpb24vZG93bmxvYWQvODc4OA==.html
  potentials: https://zenodo.org/records/6600619/files/raw-potentials.zip?download=1
  heat-pump-characteristics: https://sandbox.zenodo.org/records/45378/files/wamak-heat-pump-characteristics.nc

parameters:
  heat:
    tech-efficiencies:
      space_heat:
        gas-eff: 0.97  # [@DEA:2017]
        oil-eff: 0.9  # [@DEA:2017]
        solid-fossil-eff: 0.8 # Assume same as biofuel
        biofuel-eff: 0.8  # [@DEA:2017][@Mermoud:2015][@Chandrasekaran:2013]
        solar-thermal-eff: 1  # Eurostat energy balances method
        electricity-eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
      hot_water:
          gas-eff: 0.97  # [@DEA:2017]
          oil-eff: 0.9  # [@DEA:2017]
          solid-fossil-eff: 0.8 # Assume same as biofuel
          biofuel-eff: 0.8  # [@DEA:2017][@Mermoud:2015][@Chandrasekaran:2013]
          solar-thermal-eff: 1  # Eurostat energy balances method
          electricity-eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
      cooking:
          gas-eff: 0.28  # [@Karunanithy:2016]
          oil-eff: 0.28  # [@Karunanithy:2016], assuming oil == gas efficiency
          solid-fossil-eff: 0.15 # [@Ramanathan:1994] scaled down 60%, based on values calculated by [@Karunanithy:2016]
          biofuel-eff: 0.1 # [@Ramanathan:1994] scaled down 60%, based on values calculated by [@Karunanithy:2016]
          electricity-eff: 0.5  # [@Karunanithy:2016] based on 2/3 40% efficient direct electric, 1/3 70% efficient induction
    sfh-mfh-shares:  # derived from https://doi.org/10.2908/CENS_11DWOB_R3 using EFTA total dwelling data.
      MFH: 0.45
      SFH: 0.55
  heat-pump:
    sink-temperature:  # All values are assumed.
      underfloor: 35
      radiator-large: 50
      radiator-conventional: 65
      hot-water: 60
    space-heat-sink-shares:  # All values are assumed.
      underfloor: 0.1
      radiator-large: 0.15
      radiator-conventional: 0.75
    heat-pump-shares:  # see https://stats.ehpa.org, 2018 market data assuming current ashp = air-to-air AND air-to-water
      ashp: 0.9
      gshp: 0.1
    correction-factor: 0.85  # [@Ruhnau:2019]

scope:
  spatial:
    countries:
      - "Austria"
      - "Belgium"
      - "Bulgaria"
      - "Croatia"
      - "Cyprus"
      - "Czech Republic"
      - "Denmark"
      - "Estonia"
      - "Finland"
      - "France"
      - "Germany"
      - "Greece"
      - "Hungary"
      - "Ireland"
      - "Italy"
      - "Latvia"
      - "Lithuania"
      - "Luxembourg"
      - "Netherlands"
      - "Poland"
      - "Portugal"
      - "Romania"
      - "Slovakia"
      - "Slovenia"
      - "Spain"
      - "Sweden"
      - "United Kingdom"
      - "Albania"
      - "Bosnia and Herzegovina"
      - "Macedonia, Republic of"
      - "Montenegro"
      - "Norway"
      - "Serbia"
      - "Switzerland"
  temporal:
    first-year: 2016
    final-year: 2016

data-pre-processing:
  fill-missing-values:
    jrc-idees:
      ALB: [BGR, HRV, HUN, ROU, GRC]
      BIH: [BGR, HRV, HUN, ROU, GRC]
      MNE: [BGR, HRV, HUN, ROU, GRC]
      MKD: [BGR, HRV, HUN, ROU, GRC]
      SRB: [BGR, HRV, HUN, ROU, GRC]
      NOR: [SWE, DNK]
      CHE: [DEU, AUT, FRA, ITA]

scaling-factors: # values are tuned for models with a few hours resolution and one year duration
  power: 0.00001 # from MW(h) to 100 GW(h)