# This is the default configuration of the heat module
resolution:
  national:
    uri: "https://www.dropbox.com/scl/fi/sjjisuqnzck2mhxs9jca7/units-national.geojson?rlkey=rv0q1exsytxws3gfvankbt9p7&dl=0"
temporal-scope:
  first-year: 2016
  final-year: 2016
parameters:
  heat:
    tech-efficiencies:
      space_heat:
        gas-eff: 0.97  # [@DEA:2017]
        oil-eff: 0.9  # [@DEA:2017]
        solid-fossil-eff: 0.8 # Assume same as biofuel
        biofuel-eff: 0.8  # [@DEA:2017][@Mermoud:2015][@Chandrasekaran:2013]
        solar-thermal-eff: 1  # Eurostat energy balances method
        electricity-eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
      hot_water:
          gas-eff: 0.97  # [@DEA:2017]
          oil-eff: 0.9  # [@DEA:2017]
          solid-fossil-eff: 0.8 # Assume same as biofuel
          biofuel-eff: 0.8  # [@DEA:2017][@Mermoud:2015][@Chandrasekaran:2013]
          solar-thermal-eff: 1  # Eurostat energy balances method
          electricity-eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
      cooking:
          gas-eff: 0.28  # [@Karunanithy:2016]
          oil-eff: 0.28  # [@Karunanithy:2016], assuming oil == gas efficiency
          solid-fossil-eff: 0.15 # [@Ramanathan:1994] scaled down 60%, based on values calculated by [@Karunanithy:2016]
          biofuel-eff: 0.1 # [@Ramanathan:1994] scaled down 60%, based on values calculated by [@Karunanithy:2016]
          electricity-eff: 0.5  # [@Karunanithy:2016] based on 2/3 40% efficient direct electric, 1/3 70% efficient induction
    sfh-mfh-shares:  # derived from https://doi.org/10.2908/CENS_11DWOB_R3 using EFTA total dwelling data.
      MFH: 0.45
      SFH: 0.55
  heat-pump:
    sink-temperature:  # All values are assumed.
      underfloor: 35
      radiator-large: 50
      radiator-conventional: 65
      hot-water: 60
    space-heat-sink-shares:  # All values are assumed.
      underfloor: 0.1
      radiator-large: 0.15
      radiator-conventional: 0.75
    heat-pump-shares:  # see https://stats.ehpa.org, 2018 market data assuming current ashp = air-to-air AND air-to-water
      ashp: 0.9
      gshp: 0.1
    correction-factor: 0.85  # [@Ruhnau:2019]
