data-sources:
    hydro-generation: https://zenodo.org/record/5797549/files/hydro-generation.csv?download=1
    national-phs-storage-capacities: https://zenodo.org/record/5797549/files/pumped-hydro-storage-capacities-gwh.csv?download=1
    hydro-basins: https://www.dropbox.com/sh/hmpwobbz9qixxpe/AADeU9iCgMd3ZO1KgrFmfWu6a/HydroBASINS/standard/eu/hybas_eu_lev07_v1c.zip?dl=1
    hydro-stations: https://zenodo.org/record/5215920/files/energy-modelling-toolkit/hydro-power-database-v10.zip?download=1

capacity-factors:
    min: 0.001
    max: 10 # 0.001 -> 10 leads to a numerical range of 1e5 (hourly resolution)

quality-control:
    hydro:
        scale-phs-according-to-geth-et-al: false
        station-nearest-basin-max-km: 1

# TODO: should improve the code to automatically determine countries
# and bounds based on the supplied GeoJSON file, and all intermediate
# build artefacts resolution-dependent or unit_id-dependent rather
# than bounds-dependent
scope:
    spatial:
        countries:
            - "Austria"
            - "Belgium"
            - "Bulgaria"
            - "Croatia"
            - "Cyprus"
            - "Czech Republic"
            - "Denmark"
            - "Estonia"
            - "Finland"
            - "France"
            - "Germany"
            - "Greece"
            - "Hungary"
            - "Ireland"
            - "Italy"
            - "Latvia"
            - "Lithuania"
            - "Luxembourg"
            - "Netherlands"
            - "Poland"
            - "Portugal"
            - "Romania"
            - "Slovakia"
            - "Slovenia"
            - "Spain"
            - "Sweden"
            - "United Kingdom"
            - "Albania"
            - "Bosnia and Herzegovina"
            - "Macedonia, Republic of"
            - "Montenegro"
            - "Norway"
            - "Serbia"
            - "Switzerland"
        bounds:
            x_min: -15.8
            x_max: 37
            y_min: 30
            y_max: 75
