rule atlite_cutout:
    output:
        path = "output/test.nc",
    params:
        time = "2019-05",
        x = [-9.497466600999928, -6.205947224999932],
        y = [36.96588776200008, 42.15362966000002],
        features = ["influx", "temperature"],
        cutout_offset = 1
    threads: 4
    wrapper: "file:../"
