$schema: https://json-schema.org/draft/2020-12/schema
description: "Configuration schema for 'biofuels'."
type: object
additionalProperties: false
properties:
  use_default_user_resources:
    type: boolean
    description: If True, the module will attempt to download default resource files instead of relying on custom user inputs.
