import yaml

from pathlib import Path
from snakemake.utils import min_version, validate

# Limit the snakemake version to a modern one.
min_version("8.10")

configfile: "config/default.yaml"
validate(config, workflow.source_path("schemas/config.schema.yaml"))

# We load internal settings separately so users cannot modify them.
with open(workflow.source_path("resources/internal.yaml"), "r") as f:
    internal = yaml.safe_load(f)

include: "rules/example.smk"

rule all:
    message: "Welcome to easy and collaborative energy modelling!"
    default_target: True
    input:
        rules.download_shapefile.output,
        rules.hello_world.output
