rule test:
    input:
        cutout = "cutout.nc",
        shapefile = "portugal.geojson",
        layout = "layout.nc"
    output:
        dataset = "output/dataset.nc",
        plot_profile = "output/profile.png",
        plot_max_capacity = "output/max_cap.png"
    params:
        shapefile_name_column = "state",
        tech = "pv",
        tech_kwargs = {
            "panel": "CSi",
            "orientation": "latitude_optimal",
            "per_unit": False
        }
    threads: 4
    wrapper: "file:../"
